unbind-key C-b
set-option -g prefix C-a
bind-key C-a last-window
bind-key s split-window
bind-key v split-window -h
bind-key k confirm-before -p "kill-window #W? (y/n)" kill-window
bind-key t break-pane

# tmux v2.1
set -g mouse on

set -g status-fg white
set -g status-bg black

# copy mode like vim
setw -g mode-keys vi
unbind [
bind Escape copy-mode
unbind p
bind p paste-buffer
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Fix bracketed paste problem where I was seeing [Pasted text #7 +74 lines] instead of the lines I yanked
bind-key p paste-buffer

# So that Claude etc can Ctrl+Enter and Shift+Enter
set -g extended-keys on

# yank to laptop clipboard. Also, need iTerm 2 and to allow in settings
set -g set-clipboard on

# So I can see Claudes picker
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
