unbind-key C-b
set-option -g prefix C-a
bind-key C-a last-window
bind-key s split-window
bind-key v split-window -h
bind-key k confirm-before -p "kill-window #W? (y/n)" kill-window
bind-key t break-pane

# tmux v2.1
set -g mouse on

set -g status-fg white
set -g status-bg black

# copy mode like vim
setw -g mode-keys vi
unbind [
bind Escape copy-mode
unbind p
bind p paste-buffer
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# So that Claude etc can Ctrl+Enter and Shift+Enter
set -g extended-keys on

